# Generated by Django 2.1.1 on 2018-09-21 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('penganjur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikhmasahadir', models.DateTimeField(verbose_name='Tarikh/Masa Hadir')),
                ('aktiviti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penganjur.Aktiviti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikhmasadaftar', models.DateTimeField(verbose_name='Tarikh/Masa Daftar')),
                ('aktiviti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penganjur.Aktiviti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nokp', models.CharField(blank=True, max_length=12)),
                ('notentera', models.CharField(blank=True, max_length=8)),
                ('nama', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
