# Generated by Django 2.1.1 on 2018-09-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktiviti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mula', models.DateTimeField(verbose_name='Tarikh mula')),
                ('akhir', models.DateTimeField(verbose_name='Tarikh akhir')),
                ('hadpeserta', models.IntegerField(verbose_name='Had Peserta')),
                ('tempat', models.CharField(max_length=300, verbose_name='Tempat')),
                ('tajuk', models.CharField(max_length=300, verbose_name='Tajuk')),
                ('penceramah', models.CharField(blank=True, max_length=300, null=True, verbose_name='Penceramah')),
                ('penganjur', models.CharField(max_length=300, verbose_name='Penganjur')),
                ('status', models.CharField(choices=[('TERBUKA', 'Terbuka'), ('TERTUTUP', 'Tertutup')], default='TERTUTUP', max_length=10, verbose_name='Status Anjuran')),
                ('buka', models.DateTimeField(verbose_name='Tarikh dibuka')),
                ('tutup', models.DateTimeField(verbose_name='Tarikh ditutup')),
            ],
        ),
    ]
