# Generated by Django 2.1.1 on 2018-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penganjur', '0002_auto_20180924_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktiviti',
            name='hadpeserta',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Had Peserta'),
        ),
    ]
